language: rust
rust: nightly
cache: cargo

services:
  - postgresql

before_install:
  - ## Provision database
  - psql -U postgres -f init.sql
  - command -v diesel || cargo install --force diesel_cli
  - diesel migration run

script:
  - cargo test
