language: rust
sudo: required
addons:
    apt:
        packages:
            - libssl-dev
rust: nightly
cache: cargo

before_cache: cargo install cargo-tarpaulin -f

services:
  - postgresql

before_install:
  - ## Provision database
  - psql -U postgres -f init.sql
  - command -v diesel || cargo install --force diesel_cli
  - diesel migration run

script:
  - cargo test

after_success: |
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
