[package]
authors = ["TatriX <tatrics@gmail.com>"]
name = "realworld"
version = "0.1.0"

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
dotenv = "0.9.0"
rocket = "0.3.6"
rocket_codegen = "0.3.6"
rocket_contrib = "0.3.6"
rocket_cors = "0.2.1"
serde = "1.0.26"
serde_derive = "1.0.26"
serde_json = "1.0.8"
rust-crypto = "0.2.36"
frank_jwt = "3.0.0"
chrono = {version = "0.4.0", features = ["serde"]}
diesel = {version = "1.1.1", features = ["postgres", "chrono", "r2d2"]}
validator = "0.6.3"
validator_derive = "0.6.1"
slug = "0.1.2"
rand = "0.4.2"

[dev-dependencies]
reqwest = "0.8.2"
lazy_static = "1.0.0"
hyper = "0.11.21"

[profile.dev]
opt-level = 2
